inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/application.rb"
    - "config/initializers/*"
    - "config/spring.rb"
    - "lib/tasks/*"
    - "vendor/**/*"
    - "path/ruby"
    - "config/**/*"
    - "Gemfile"
    - "spec/spec_helper.rb"
