import Footer from "./components/Footer";
import Header from "./components/Header";
import Main from "./components/Main";
import ToastWrapper from "./components/ToastWrapper";
import { Providers } from "./providers";

export const metadata = {
  title: "Webfolio-Review",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <Header />
          <Main>{children}</Main>
          <Footer />
          <ToastWrapper />
        </Providers>
      </body>
    </html>
  );
}
